# Generated by Django 5.1.1 on 2024-09-04 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fueltype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('fuel', models.CharField(choices=[('D', 'Diesel'), ('G', 'Gasoline'), ('E', 'Electric'), ('H', 'Hybrid')], default='D', max_length=1)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.truck')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
